### ISSUE TITLE
Use multibyte string functions to check string length in CollectionValidator

### ISSUE THREAD

**Issue by aanton** [Livefyre/livefyre-php-utils#11]
Assuming maximum length of the collection title is measured in characters (not in bytes), the class `CollectionValidator` should use the `mb_strlen` function to validate the title length.

Regards,
Armando

**Comment by soldnermike** [comment]
Hey Armando,

You're assumptions are correct! I will be updating this in the newest patch.

Thanks!

-Mike

**Comment by aanton** [comment]
Any updates?

**Comment by aanton** [comment]
Closed because of inactivity
