### ISSUE TITLE
Fatal error: Class 'Livefyre\Utils\UnexpectedValueException' not found in /lib/Livefyre/Utils/JWT.php on line 48

### ISSUE THREAD

**Issue by shawesome** [Livefyre/livefyre-php-utils#8]
When passing a non valid JWT to a "validateLivefyreToken" call (e.g. just an empty string). Then I see the above exception.

The reason is that the exception names in the Livefyre/Utils/JWT.php file aren't escaped to the global namespace and so my code is looking for them inside the Livefyre\Utils namespace. I've fixed this in my code by prepending "\" to each of the exception names.

An improvement to this code would be to add another check to ensure that the passed string is valid JWT before attempting to decode it.

**Comment by daegun** [comment]
Hey @shawesome, thanks for the input. I'll be taking a look into adding both parts to the library.

**Comment by daegun** [comment]
Released 2.0.2 with a fix. Closing issue.
