### ISSUE TITLE
Class 'JWT' not found 

### ISSUE THREAD

**Issue by ajliv** [Livefyre/livefyre-php-utils#9]
Getting a fatal error of "Class 'JWT' not found in /var/www/vendor/livefyre/livefyre-php-utils/src/Livefyre/Core/Network.php on line 66",

Looks like v3.0 of firebase/php-jwt was release in late July 2015, which changed the namespace of JWT. Found a similar issue here: https://github.com/auth0/auth0-PHP/issues/25

Updating the semver in composer.json should fix.

**Comment by soldnermike** [comment]
Hey ajliv, I've notice the same issue and will be patching as soon as possible. Thanks for bringing this up!

**Comment by andrepiper** [comment]
I recently downloaded Php util and ran into this error, i saw the bug date of Sep. 2015. Is there a fix for the error?
